{% set name = "ee_extra" %}
{% set version = "2025.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ee_extra-{{ version }}.tar.gz
  sha256: 3d3d0f5ed2d755761e3fc3157133e8d77e6890587355125238b11d4933347698

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=3.8
    - earthengine-api >=1.5.24

test:
  imports:
    - ee_extra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/r-earthengine/ee_extra
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A ninja python package that unifies the Google Earth Engine ecosystem.
  doc_url: https://ee-extra.readthedocs.io/
  dev_url: https://github.com/r-earthengine/ee_extra

extra:
  recipe-maintainers:
    - davemlz
    - csaybar
