{% set name = "ee_extra" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7526863a40731b8e78e1e6dbb1c97e4be63ce488f6bbd42cb2b442a3fb14945

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - numpy
    - python >=3.6

test:
  imports:
    - ee_extra
    - ee_extra.Image
    - ee_extra.ImageCollection
    - ee_extra.JavaScript
    - ee_extra.STAC
    - ee_extra.Spectral
    - ee_extra.TimeSeries

about:
  home: https://github.com/r-earthengine/ee_extra
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A ninja python package that unifies the Google Earth Engine ecosystem.
  doc_url: https://ee-extra.readthedocs.io/
  dev_url: https://github.com/r-earthengine/ee_extra

extra:
  recipe-maintainers:
    - davemlz
    - csaybar
