{% set name = "ee-extra" %}
{% set version = "2025.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ee_extra-{{ version }}.tar.gz
  sha256: 623a920c67200dfe22482530d7af4db30992eb56f0507d25c7e7c8e6dca07c96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=3.8
    - earthengine-api >=1.5.24

test:
  imports:
    - ee_extra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/r-earthengine/ee_extra
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A ninja python package that unifies the Google Earth Engine ecosystem.
  doc_url: https://ee-extra.readthedocs.io/
  dev_url: https://github.com/r-earthengine/ee_extra

extra:
  recipe-maintainers:
    - davemlz
    - csaybar
